version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/actions/iemwebfarm"
    schedule:
      interval: "monthly"
    labels:
      - "Bot"
    groups:
      github-actions:
        patterns:
          - '*'
