name: 'IEM Webfarm Micromamba + Apache Setup'
description: 'Prepare micromamba environment and run iemwebfarm.sh (single-purpose action).'

inputs:
  environment-file:
    description: 'Path to the micromamba/conda environment file in the consumer repo'
    required: false
    default: 'environment.yml'
  environment-name:
    description: 'Name of the environment to create/use'
    required: false
    default: 'prod'
  python-version:
    description: 'Python version to create in the environment (e.g. 3.14)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # This checks out the caller repo, since we need to see environment file.
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: ${{ inputs.environment-file }}
        init-shell: >-
          bash
        condarc: |
          channels:
            - conda-forge
        create-args: >-
          python=${{ inputs.python-version }}
          mamba
        environment-name: ${{ inputs.environment-name }}
        cache-environment: true

    # Check if a pip_requirements.txt file exists
    - name: Pip install needed
      id: pip_install_needed
      shell: bash -l {0}
      run: |
        if [[ -f "pip_requirements.txt" ]]; then
          echo "Found pip_requirements.txt, will run pip install."
          echo "pip_requirements=true" >> $GITHUB_OUTPUT
        else
          echo "No pip_requirements.txt found, skipping pip install."
          echo "pip_requirements=false" >> $GITHUB_OUTPUT
        fi

    - name: Optionally run pip install
      if: ${{ steps.pip_install_needed.outputs.pip_requirements == 'true' }}
      shell: bash -l {0}
      run: |
        set -euo pipefail
        echo "Running pip install from pip_requirements.txt."
        mamba run -n "${{ inputs.environment-name }}" python -m pip install -r pip_requirements.txt --no-deps

    - name: Run iemwebfarm provisioning inside environment
      shell: bash -l {0}
      run: |
        set -euo pipefail
        cd "${{ github.action_path }}"
        mamba run -n "${{ inputs.environment-name }}" bash -l "iemwebfarm.sh"
