[Service]
  # 4 Dec 2025: libexpat needed as latest python builds use newer lib
  # 18 Mar 2026: careful between libssl3.so and libssl.so.3
  Environment=LD_PRELOAD=/home/runner/micromamba/envs/prod/lib/libexpat.so.1:/home/runner/micromamba/envs/prod/lib/libssl.so.3:/home/runner/micromamba/envs/prod/lib/libcurl.so
