name: Install and Test
on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main
jobs:
  build-linux:
    name: Python (${{ matrix.PYTHON_VERSION }})
    runs-on: ubuntu-latest
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -l {0}
    strategy:
      matrix:
        PYTHON_VERSION: ["3.10", "3.13", "3.14"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    steps:
    - uses: actions/checkout@v6

    - name: Setup IEM Webfarm environment
      uses: ./actions/iemwebfarm
      with:
        environment-file: environment.yml
        python-version: "${{ matrix.PYTHON_VERSION }}"
        environment-name: prod
